# Generated by Django 3.0.2 on 2020-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typeday', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('windbearing', models.FloatField()),
                ('windgust', models.FloatField()),
                ('rain_prob', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typeday', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('windbearing', models.FloatField()),
                ('windgust', models.FloatField()),
                ('rain_prob', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
